config/routes.rb
Rails.application.routes.draw do
  resources :cakes
  root "cakes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cake.rb
class Cake < ApplicationRecord
  validates :name, :price, presence: :true
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
  before_action :find_cake, only: [:show, :edit, :update, :destroy]

  def index
    @cakes = Cake.all
  end

  def new
    @cake = Cake.new
  end

  def create
    @cake = Cake.new(cake_params)
    if @cake.save
      redirect_to cakes_path, notice: "新增成功！！！！"
    else
      render :new, alert: "新增失敗！！！！"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @cake.update(cake_params)
      redirect_to cakes_path, notice: "成功修改！！！"
    else
      render :edit, notice: "修改失敗！！！"
    end
  end

  def destroy
    @cake.destroy
    redirect_to cakes_path, notice: "刪除完成！！！！"
  end

  private

  def cake_params
    params.require(:cake).permit(:name, :price)
  end

  def find_cake
    @cake = Cake.find_by(id: params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :room_find, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path, notice: "成功新增房源"
    else
      render :new, notice: "新增房源失敗"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to room_path, notice: "成功修改"
    else
      render :edit, notice: "修改失敗"
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_path, notice: "已成功刪除"
  end

  private

  def room_params
    params.require(:room).permit(:name, :price)
  end

  def room_find
    @room = Room.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cakes_helper.rb
module CakesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/cakes/index.html.erb
<h2>INDEX</h2>
<%= link_to "新增蛋糕", new_cake_path %>
<% @cakes.each do |c| %>
<ul>
<li>
<%= link_to c.name, cake_path(c.id) %>
<%= link_to "編輯", edit_cake_path(c.id) %>
<%= link_to "刪除", cake_path(c.id), method: "delete", data: { confirm: "確定刪除？" } %>
</ul>
<% end %>

app/views/cakes/new.html.erb
<h2>新增蛋糕</h2>

<%= form_with model: @cake do |f| %>
<div>
<%= f.label :name %>
<%= f.text_field :name %>
</div>
<div>
<%= f.label :price %>
<%= f.text_field :price %>
</div>
<%= f.submit %>
<% end %>

app/views/cakes/show.html.erb
<h2>蛋糕：<%= @cake.name %></h2>
<h2>價格：<%= @cake.price %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice1123</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/rooms/edit.html.erb
<h1>修改房源</h1>

<%= form_with model: @room do |r| %>
<div>
<%= r.label :name %>
<%= r.text_field :name %>
</div>
<div>
<%= r.label :price %>
<%= r.text_field :price %>
</div>
<%= r.submit %>
<% end %>

app/views/rooms/index.html.erb
<h1>Index</h1>
<%= link_to "新增房源", new_room_path %>

<ul>
<% @rooms.each do |r| %>
<li>
<%= r.id %>
<%= link_to r.name, room_path(r.id) %>
<%= r.price %>
<%= link_to "修改", edit_room_path(r.id) %>
<%= link_to "刪除", room_path(r.id), method: "delete", data: { confirm: "確定刪除？" } %>
</li>
<% end %>
</ul>

app/views/rooms/new.html.erb
<h1>新增房源</h1>

<%= form_with model: @room do |r| %>
<div>
<%= r.label :name %>
<%= r.text_field :name %>
</div>
<div>
<%= r.label :price %>
<%= r.text_field :price %>
</div>
<%= r.submit %>
<% end %>

app/views/rooms/show.html.erb
<h1><%= @room.name %></h1>
<%= @room.price %>

app/views/shared/_flash.html.erb
<% if flash.any? %>
    <div style="background-color: green; color: white">
      <%= notice %>
    </div>
    <div style="background-color: red; color: white">
      <%= alert %>
    </div>
<% end %>